global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    experiment: 'cardinality-test'

rule_files:
  # - "alert_rules.yml"

scrape_configs:
  - job_name: 'genmetrics'
    static_configs:
      - targets: ['genmetrics:8090']
    scrape_interval: 10s
    scrape_timeout: 10s
    metrics_path: '/metrics'

  # - job_name: 'prometheus'
  #   static_configs:
  #     - targets: ['localhost:9090']
  #   scrape_interval: 5s
  #   scrape_timeout: 5s

  # - job_name: 'node-exporter'
  #   static_configs:
  #     - targets: ['node-exporter:9100']
  #   scrape_interval: 5s
  #   scrape_timeout: 5s
