global:
  scrape_interval: 20s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093  # O endere√ßo do seu Alertmanager
          
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'app_exporter'
    static_configs:
      - targets: ['flask-app:5000']
