receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
        max_recv_msg_size_mib: 32
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1000
    send_batch_max_size: 1000

  attributes:
    actions:
      - key: kafka.partition.key
        action: insert
        from_attribute: service.name

exporters:

  kafka/metrics:
    brokers:
      - kafka:29092
    topic: otel-metrics
    encoding: otlp_proto
    # encoding: otlp_json
    protocol_version: 2.8.0
    
  kafka/traces:
    brokers:
      - kafka:29092
    topic: otel-traces
    encoding: otlp_proto
    protocol_version: 2.8.0

  debug:
    verbosity: detailed


service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [kafka/traces, debug]
      
    metrics:
      receivers: [otlp]
      processors: [attributes, batch]
      exporters: [kafka/metrics, debug]

  telemetry:
    metrics:
      level: detailed
      address: 0.0.0.0:9115
    logs:
      level: WARN
      output_paths: ["stdout"]