dist:
  name: otelcol-custom
  description: "Custom OTEL Collector with Simple Processor"
  output_path: ./dist-logscore

  module: github.com/myuser/my-otel-collector
  version: "0.1.0"
  otelcol_version: "0.128.0"

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.128.0

processors:
  - gomod: github.com/myuser/my-otel-collector/processors/logscore v0.1.0
    path: ./processors/logscore

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.128.0
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.128.0