global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 1m
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node_exporter"
    scrape_interval: 10s
    static_configs:
      - targets: ["node_exporter:9100"]

  - job_name: "opentelemetry_metrics"
    scrape_interval: 10s
    static_configs:
      - targets: ["otel-collector:8889"]

  - job_name: "opentelemetry_internal"
    scrape_interval: 10s
    static_configs:
      - targets: ["otel-collector:8888"]
