dist:
  name: sherlock-collector
  description: "Custom collector"
  output_path: ./dist
  module: github.com/apolzek/sherlock-collector
  version: "0.1.0"
  otelcol_version: "0.130.1"

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.130.1
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver v0.131.0


processors:
  - gomod: github.com/apolzek/sherlock-collector/processors/schemadetectorprocessor v0.0.1
    path: ./processors/schemadetectorprocessor
  - gomod: github.com/apolzek/sherlock-collector/processors/sleepprocessor v0.0.1
    path: ./processors/sleepprocessor

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.130.1
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.130.1

