dist:
  name: custom-collector
  description: "Custom collector"
  output_path: ./dist
  module: github.com/apolzek/custom-collector
  version: "0.1.0"
  otelcol_version: "0.135.0"

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.135.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver v0.135.0

processors:
  - gomod: github.com/apolzek/sherlock-collector/processors/sleepprocessor v0.0.1
    path: ./processors/sleepprocessor
  - gomod: github.com/apolzek/sherlock-collector/processors/alertprocessor v0.0.1
    path: ./processors/alertprocessor

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.135.0
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.135.0

