receivers:
  kafka/traces:
    brokers: ["kafka:9092"]
    topic: otlp_spans
    autocommit:
      enable: false
    # message_marking: 
    #   after: true
    #   on_error: false

exporters:
  otlp/jaeger:
    endpoint: "http://jaeger:4317"
    tls:
      insecure: true

processors:
  batch:
    send_batch_size: 10
    timeout: 1s

service:
  telemetry:
    logs:
      level: debug
  pipelines:
    traces:
      receivers: [kafka/traces]
      processors: [batch]
      exporters: [otlp/jaeger]
