global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:

  - job_name: 'otel-collector-producer'
    static_configs:
      - targets: ['opentelemetry-collector-producer:9115']
        labels:
          collector: 'producer'

  - job_name: 'otel-collector-consumer'
    static_configs:
      - targets: ['opentelemetry-collector-consumer:9115']
        labels:
          collector: 'consumer'

  - job_name: 'otel-consumer-prometheus'
    static_configs:
      - targets: ['opentelemetry-collector-consumer:9005']
        labels:
          collector: 'consumer-prometheus'

  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']
        labels:
          service: 'kafka'

